[2021-02-28 09:18:09,061] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ga_to_postgres_dag.store_ga_csv 2021-02-28T08:18:04.815680+00:00 [queued]>
[2021-02-28 09:18:09,066] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ga_to_postgres_dag.store_ga_csv 2021-02-28T08:18:04.815680+00:00 [queued]>
[2021-02-28 09:18:09,067] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-28 09:18:09,067] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-28 09:18:09,067] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-28 09:18:09,072] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): store_ga_csv> on 2021-02-28T08:18:04.815680+00:00
[2021-02-28 09:18:09,074] {standard_task_runner.py:52} INFO - Started process 35261 to run task
[2021-02-28 09:18:09,079] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ga_to_postgres_dag', 'store_ga_csv', '2021-02-28T08:18:04.815680+00:00', '--job-id', '23', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ga_to_postgres_dag.py', '--cfg-path', '/var/folders/fh/z0rf64gj7d93005s7pxrkwm40000gn/T/tmpb98kl1j7', '--error-file', '/var/folders/fh/z0rf64gj7d93005s7pxrkwm40000gn/T/tmp_4e9myi7']
[2021-02-28 09:18:09,080] {standard_task_runner.py:77} INFO - Job 23: Subtask store_ga_csv
[2021-02-28 09:18:09,107] {logging_mixin.py:104} INFO - Running <TaskInstance: ga_to_postgres_dag.store_ga_csv 2021-02-28T08:18:04.815680+00:00 [running]> on host 120.0.168.192.in-addr.arpa
[2021-02-28 09:18:09,130] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ga_to_postgres_dag
AIRFLOW_CTX_TASK_ID=store_ga_csv
AIRFLOW_CTX_EXECUTION_DATE=2021-02-28T08:18:04.815680+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-28T08:18:04.815680+00:00
[2021-02-28 09:18:09,131] {logging_mixin.py:104} INFO - save_data_csv
[2021-02-28 09:18:09,131] {python.py:118} INFO - Done. Returned value was: None
[2021-02-28 09:18:09,134] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=ga_to_postgres_dag, task_id=store_ga_csv, execution_date=20210228T081804, start_date=20210228T081809, end_date=20210228T081809
[2021-02-28 09:18:09,146] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-28 09:18:09,180] {local_task_job.py:146} INFO - Task exited with return code 0
