[2021-02-28 09:18:07,178] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ga_to_postgres_dag.check_api 2021-02-28T08:18:04.815680+00:00 [queued]>
[2021-02-28 09:18:07,184] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ga_to_postgres_dag.check_api 2021-02-28T08:18:04.815680+00:00 [queued]>
[2021-02-28 09:18:07,184] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-28 09:18:07,184] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-28 09:18:07,184] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-28 09:18:07,189] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): check_api> on 2021-02-28T08:18:04.815680+00:00
[2021-02-28 09:18:07,191] {standard_task_runner.py:52} INFO - Started process 35257 to run task
[2021-02-28 09:18:07,197] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ga_to_postgres_dag', 'check_api', '2021-02-28T08:18:04.815680+00:00', '--job-id', '21', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ga_to_postgres_dag.py', '--cfg-path', '/var/folders/fh/z0rf64gj7d93005s7pxrkwm40000gn/T/tmpo1osgng9', '--error-file', '/var/folders/fh/z0rf64gj7d93005s7pxrkwm40000gn/T/tmp50kw5614']
[2021-02-28 09:18:07,198] {standard_task_runner.py:77} INFO - Job 21: Subtask check_api
[2021-02-28 09:18:07,226] {logging_mixin.py:104} INFO - Running <TaskInstance: ga_to_postgres_dag.check_api 2021-02-28T08:18:04.815680+00:00 [running]> on host 120.0.168.192.in-addr.arpa
[2021-02-28 09:18:07,250] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ga_to_postgres_dag
AIRFLOW_CTX_TASK_ID=check_api
AIRFLOW_CTX_EXECUTION_DATE=2021-02-28T08:18:04.815680+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-28T08:18:04.815680+00:00
[2021-02-28 09:18:07,251] {logging_mixin.py:104} INFO - check api
[2021-02-28 09:18:07,251] {python.py:118} INFO - Done. Returned value was: None
[2021-02-28 09:18:07,254] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=ga_to_postgres_dag, task_id=check_api, execution_date=20210228T081804, start_date=20210228T081807, end_date=20210228T081807
[2021-02-28 09:18:07,266] {taskinstance.py:1220} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2021-02-28 09:18:07,292] {local_task_job.py:146} INFO - Task exited with return code 0
