[2021-02-28 09:18:09,995] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ga_to_postgres_dag.csv_to_postgres 2021-02-28T08:18:04.815680+00:00 [queued]>
[2021-02-28 09:18:10,000] {taskinstance.py:851} INFO - Dependencies all met for <TaskInstance: ga_to_postgres_dag.csv_to_postgres 2021-02-28T08:18:04.815680+00:00 [queued]>
[2021-02-28 09:18:10,000] {taskinstance.py:1042} INFO - 
--------------------------------------------------------------------------------
[2021-02-28 09:18:10,000] {taskinstance.py:1043} INFO - Starting attempt 1 of 1
[2021-02-28 09:18:10,000] {taskinstance.py:1044} INFO - 
--------------------------------------------------------------------------------
[2021-02-28 09:18:10,005] {taskinstance.py:1063} INFO - Executing <Task(PythonOperator): csv_to_postgres> on 2021-02-28T08:18:04.815680+00:00
[2021-02-28 09:18:10,006] {standard_task_runner.py:52} INFO - Started process 35263 to run task
[2021-02-28 09:18:10,012] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'ga_to_postgres_dag', 'csv_to_postgres', '2021-02-28T08:18:04.815680+00:00', '--job-id', '24', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/ga_to_postgres_dag.py', '--cfg-path', '/var/folders/fh/z0rf64gj7d93005s7pxrkwm40000gn/T/tmp4srzx2g2', '--error-file', '/var/folders/fh/z0rf64gj7d93005s7pxrkwm40000gn/T/tmpo9tlziwz']
[2021-02-28 09:18:10,014] {standard_task_runner.py:77} INFO - Job 24: Subtask csv_to_postgres
[2021-02-28 09:18:10,042] {logging_mixin.py:104} INFO - Running <TaskInstance: ga_to_postgres_dag.csv_to_postgres 2021-02-28T08:18:04.815680+00:00 [running]> on host 120.0.168.192.in-addr.arpa
[2021-02-28 09:18:10,065] {taskinstance.py:1255} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=ga_to_postgres_dag
AIRFLOW_CTX_TASK_ID=csv_to_postgres
AIRFLOW_CTX_EXECUTION_DATE=2021-02-28T08:18:04.815680+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-02-28T08:18:04.815680+00:00
[2021-02-28 09:18:10,066] {logging_mixin.py:104} INFO - csv to pg
[2021-02-28 09:18:10,066] {python.py:118} INFO - Done. Returned value was: None
[2021-02-28 09:18:10,069] {taskinstance.py:1159} INFO - Marking task as SUCCESS. dag_id=ga_to_postgres_dag, task_id=csv_to_postgres, execution_date=20210228T081804, start_date=20210228T081809, end_date=20210228T081810
[2021-02-28 09:18:10,079] {taskinstance.py:1220} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2021-02-28 09:18:10,107] {local_task_job.py:146} INFO - Task exited with return code 0
